import { jsPDF } from "jspdf";

export function downloadBidPdf({ bid, bidder, tender, documents = [] }) {
  const doc = new jsPDF();
  const margin = 18;
  let y = 20;

  const line = (label, value) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text(String(label), margin, y);
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(String(value ?? "—"), 165);
    doc.text(lines, margin + 42, y);
    y += Math.max(7, lines.length * 5);
  };

  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  doc.text("ProcureShield AI", margin, y);
  y += 7;
  doc.setFontSize(12);
  doc.text("Bid Submission Record", margin, y);
  y += 10;

  doc.setDrawColor(210, 215, 220);
  doc.line(margin, y, 192, y);
  y += 9;

  line("Bid ID", bid?.bid_id);
  line("Tender ID", bid?.tender_id);
  line("Tender", tender?.title || bid?.tender_id);
  line("Department", tender?.department);
  line("Category", bid?.category || tender?.category);
  line("Bidder", bidder?.company_name || bid?.bidder_name || bid?.bidder_company_name);
  line("Bid Amount", bid?.bid_amount != null ? `₹ ${Number(bid.bid_amount).toLocaleString("en-IN")}` : "—");
  line("Submitted", bid?.submission_date);
  line("Verification Status", bid?.verification_status);
  line("Risk", bid?.risk_score != null ? `${bid.risk_score}/100 · ${bid.risk_category || "Unclassified"}` : "Pending analysis");

  y += 4;
  doc.setFont("helvetica", "bold");
  doc.text("Submitted Documents", margin, y);
  y += 7;
  doc.setFont("helvetica", "normal");

  const names = documents.length
    ? documents.map((d) => typeof d === "string" ? d : d.name)
    : (bid?.submitted_documents || []);
  names.forEach((name, index) => {
    const lines = doc.splitTextToSize(`${index + 1}. ${name}`, 165);
    doc.text(lines, margin + 3, y);
    y += Math.max(6, lines.length * 5);
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
  });

  y += 8;
  doc.setFontSize(8);
  doc.setTextColor(100, 110, 120);
  doc.text(
    "Generated by ProcureShield AI. This document is a bid submission record; officer decisions remain subject to verification.",
    margin,
    y,
    { maxWidth: 175 }
  );

  const safeId = String(bid?.bid_id || "bid").replace(/[^a-zA-Z0-9_-]/g, "_");
  doc.save(`ProcureShield-${safeId}.pdf`);
}
