import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { ShieldCheck, Loader2, Mail, LockKeyhole, Building2, BriefcaseBusiness } from "lucide-react";
import { useApp } from "../store.jsx";
import { api } from "../api.js";

const CONFIG={officer:{title:"Officer Login",subtitle:"Access tender management, bid verification and risk analysis.",icon:Building2,username:"admin",password:"admin123",label:"Officer demo",destination:"/app/officer"},bidder:{title:"Bidder Login",subtitle:"Access tenders, document verification and bid submission.",icon:BriefcaseBusiness,username:"bidder",password:"bidder123",label:"Bidder demo",destination:"/bidder"}};

export default function Login({role="officer"}){
 const c=CONFIG[role]||CONFIG.officer,RoleIcon=c.icon;
 const [username,setUsername]=useState(c.username),[password,setPassword]=useState(c.password),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 const {login}=useApp();const navigate=useNavigate();
 async function handleSubmit(e){e.preventDefault();setError("");setLoading(true);try{const res=await api.login(username,password);if(role==="officer"&&res.officer?.role!=="Procurement Officer")throw new Error("Please use an officer account for the Officer Portal.");if(role==="bidder"&&res.officer?.role!=="Bidder")throw new Error("Please use a bidder account for the Bidder Portal.");login(res.officer,res.token);navigate(c.destination);}catch(err){setError(err.message||"Login failed");}finally{setLoading(false);}}
 async function instantLogin(targetRole){const target=CONFIG[targetRole];setError("");setLoading(true);try{const res=await api.login(target.username,target.password);login(res.officer,res.token);navigate(target.destination);}catch(err){setError(err.message||"Demo login failed");}finally{setLoading(false);}}
 return <div className="min-h-screen bg-slate-100 px-4 py-8 sm:py-12"><div className="mx-auto flex min-h-[calc(100vh-4rem)] w-full max-w-md items-center justify-center"><div className="w-full">
  <div className="mb-7 text-center"><div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-brand-700 shadow-sm"><ShieldCheck size={28} className="text-white"/></div><h1 className="text-3xl font-bold tracking-tight text-slate-900">ProcureShield AI</h1><p className="mt-2 text-base text-slate-500">{c.title}</p></div>
  <div className="rounded-2xl border border-slate-200 bg-white p-7 shadow-card sm:p-8">
      <div className="mb-6 flex items-center gap-3 border-b border-slate-100 pb-5"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand-50 text-brand-700"><RoleIcon size={19}/></div><div><div className="text-sm font-semibold text-slate-900">{c.title}</div><div className="text-xs text-slate-500">{c.subtitle}</div></div></div>
   <div className="mb-6 rounded-2xl border border-brand-200 bg-slate-50 p-4"><div className="mb-3 flex items-center gap-2 text-sm font-bold text-slate-800"><span className="text-lg">⚡</span> Instant Demo Roles</div><div className="grid grid-cols-2 gap-3"><button type="button" disabled={loading} onClick={()=>instantLogin("officer")} className="rounded-xl border border-slate-200 bg-white p-3 text-left transition hover:border-brand-300 hover:shadow-sm disabled:cursor-not-allowed disabled:opacity-60"><div className="mb-1 flex h-8 w-8 items-center justify-center rounded-lg bg-brand-50 text-brand-700"><Building2 size={16}/></div><div className="text-sm font-semibold text-slate-900">Officer</div><div className="text-xs text-slate-500">Vikram Deshmukh</div><div className="mt-2 text-[11px] font-medium text-brand-700">Enter portal →</div></button><button type="button" disabled={loading} onClick={()=>instantLogin("bidder")} className="rounded-xl border border-slate-200 bg-white p-3 text-left transition hover:border-brand-300 hover:shadow-sm disabled:cursor-not-allowed disabled:opacity-60"><div className="mb-1 flex h-8 w-8 items-center justify-center rounded-lg bg-brand-50 text-brand-700"><BriefcaseBusiness size={16}/></div><div className="text-sm font-semibold text-slate-900">Bidder</div><div className="text-xs text-slate-500">Demo Bidder</div><div className="mt-2 text-[11px] font-medium text-brand-700">Enter portal →</div></button></div><div className="mt-3 text-center text-xs text-slate-400">One click opens the selected demo portal.</div></div>
   <form onSubmit={handleSubmit} className="space-y-5">
    <div><label className="mb-2 block text-sm font-semibold text-slate-700">Email / Username</label><div className="relative"><Mail size={18} className="absolute left-3.5 top-3.5 text-slate-400"/><input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username" className="w-full rounded-xl border border-slate-300 bg-white py-3 pl-11 pr-4 text-sm text-slate-900 outline-none transition focus:border-brand-500 focus:ring-2 focus:ring-brand-100" placeholder="Enter your username"/></div></div>
    <div><label className="mb-2 block text-sm font-semibold text-slate-700">Password</label><div className="relative"><LockKeyhole size={18} className="absolute left-3.5 top-3.5 text-slate-400"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" className="w-full rounded-xl border border-slate-300 bg-white py-3 pl-11 pr-4 text-sm text-slate-900 outline-none transition focus:border-brand-500 focus:ring-2 focus:ring-brand-100" placeholder="Enter your password"/></div></div>
    {error&&<div className="rounded-xl border border-red-200 bg-red-50 px-3.5 py-3 text-sm text-red-700">{error}</div>}
    <button type="submit" disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-xl bg-brand-700 py-3.5 text-base font-semibold text-white transition hover:bg-brand-800 disabled:cursor-not-allowed disabled:opacity-60">{loading&&<Loader2 size={18} className="animate-spin"/>}{loading?"Signing in...":"Sign In"}{!loading&&<span aria-hidden="true">→</span>}</button>
   </form>
   <div className="mb-6 rounded-2xl border border-brand-200 bg-slate-50 p-4"><div className="mb-3 flex items-center gap-2 text-sm font-bold text-slate-800"><span className="text-lg">⚡</span> Instant Demo Roles</div><div className="grid grid-cols-2 gap-3"><button type="button" disabled={loading} onClick={()=>instantLogin("officer")} className="rounded-xl border border-slate-200 bg-white p-3 text-left transition hover:border-brand-300 hover:shadow-sm disabled:cursor-not-allowed disabled:opacity-60"><div className="mb-1 flex h-8 w-8 items-center justify-center rounded-lg bg-brand-50 text-brand-700"><Building2 size={16}/></div><div className="text-sm font-semibold text-slate-900">Officer</div><div className="text-xs text-slate-500">Vikram Deshmukh</div><div className="mt-2 text-[11px] font-medium text-brand-700">Enter portal →</div></button><button type="button" disabled={loading} onClick={()=>instantLogin("bidder")} className="rounded-xl border border-slate-200 bg-white p-3 text-left transition hover:border-brand-300 hover:shadow-sm disabled:cursor-not-allowed disabled:opacity-60"><div className="mb-1 flex h-8 w-8 items-center justify-center rounded-lg bg-brand-50 text-brand-700"><BriefcaseBusiness size={16}/></div><div className="text-sm font-semibold text-slate-900">Bidder</div><div className="text-xs text-slate-500">Demo Bidder</div><div className="mt-2 text-[11px] font-medium text-brand-700">Enter portal →</div></button></div><div className="mt-3 text-center text-xs text-slate-400">One click opens the selected demo portal.</div></div>
   <button type="button" onClick={()=>navigate("/")} className="mt-5 w-full text-center text-sm font-medium text-brand-700 hover:text-brand-800">← Back to portal selection</button>
  </div><p className="mt-5 text-center text-xs text-slate-400">ProcureShield AI · Prototype / sandbox</p>
 </div></div></div>;
}